### PR TITLE
Add cross-platform support for configuration rehashing

### PR DESCRIPTION
**Pull request by delthas**
Tested, works on Windows.

### CODE REVIEW

**Comment by delthas** [comment]
The CI should probably be run with Rust nightly :p

**Comment by delthas** [comment]
Let me know if you're interested in a sourcehut CI file for building ellidri targeting Windows on Linux.

**Comment by hhirtz** [comment]
> The CI should probably be run with Rust nightly :p

Yes, I was using alpine/3.11's rust 1.39 to have some stability but it
didn't work well with SQL drivers (notably postgres which required
1.41). I'll update the build script to use alpine edge.

> Let me know if you're interested in a sourcehut CI file for building
> ellidri targeting Windows on Linux.

Please send a patch, I'll merge it in.

**Comment by delthas** [comment]
Added in 13d162f74ff9af9aa855d9abe390bc17ae65936a

**Comment by delthas** [comment]
OK. My manifest:
```
image: archlinux
sources:
    - https://git.sr.ht/~taiite/ellidri.git
tasks:
    - build: |
        printf '[ownstuff]\nServer = https://martchus.no-ip.biz/repo/arch/$repo/os/$arch\nSigLevel = PackageOptional\n' | sudo tee -a /etc/pacman.conf
        sudo pacman --noconfirm -Syu mingw-w64-gcc
        printf '[archlinuxcn]\nServer = http://repo.archlinuxcn.org/$arch\nSigLevel = Never\n' | sudo tee -a /etc/pacman.conf
        sudo pacman --noconfirm -Syu cargo-nightly rust-nightly rust-std-nightly-x86_64-pc-windows-gnu
        mkdir -p ~/.cargo
        printf '[target.x86_64-pc-windows-gnu]\nlinker = "/usr/bin/x86_64-w64-mingw32-gcc"\nar = "/usr/x86_64-w64-mingw32/bin/ar"' > ~/.cargo/config
        cd ellidri
        cargo build --release --locked --target "x86_64-pc-windows-gnu"
		# exe is built at target/x86_64-pc-windows-gnu/release/ellidri.exe
		# for example, deploy it somewhere
        # scp -o StrictHostKeyChecking=no -q target/x86_64-pc-windows-gnu/release/ellidri.exe user@example.com:/srv/http/ellidri.exe
```

Feel free to edit it and integrate it into the repository.

**Comment by hhirtz** [comment]
Added in 43d8f0cd30b60e9a823d36371ab1c9f079b6c018

**Pull request closed without merging**
